### ISSUE TITLE
Successfully installed the dependencies but could not build the project.

### ISSUE THREAD

**Issue by Chaoyism** [snkas/hypatia#22]
### Problem

Hi! I am having problems trying to build the project and run the tests. After installing dependencies with no errors, I could not build the project.

![build_result](https://user-images.githubusercontent.com/70335610/232734962-7a066e97-3958-4417-bf2f-0ad51ba5861e.jpg)

### Environment

The environment is **Ubuntu 22.04** and **Python 3.10.6**. 

### Reproduction

To reproduce this issue, firstly run **sudo apt-get update** and **sudo apt-get upgrade** in a new **Ubuntu 22.04 or 20.04** virtual machine running on **VirtualBox-7.0.6-155176-Win**.

The new system did not have pip by default, so directly installing the dependencies would not proceed, and pip was installed with **apt-get install python3-pip**.

After pip was installed, **bash hypatia_install_dependencies.sh** could be correctly executed, and **bash hypatia_build.sh** would get errors as the screenshot above.

### Guess

The problem could be led to by two possible reasons.

The first reason is that the makefile treated all warnings as errors as shown in the screenshot above.

The second reason is that there were some necessary modules not installed in my environment or some files were missed in the repository, as the **not found** and **not enabled** error messages implied when building the project.
![notfound](https://user-images.githubusercontent.com/70335610/232738050-4c1b275d-a5f0-4c23-80a5-67bae0a4bda1.jpg)
![notenabled](https://user-images.githubusercontent.com/70335610/232738038-96866888-aeb8-4617-b4dc-c11cb8cef390.jpg)

Could anyone who had successfully built the project kindly provide their environment or any hints on how to solve this problem? Thank you very much in advance!

**Comment by Chaoyism** [comment]
Hi! Eventually I've successfully run the test. The problem of my environment is that the 'python' command in the terminal was not linked to python3, which was the default setting of Ubuntu 20/22. I suggest everyone who is going to use Hypatia to configure the environment in the following way:

1. Install **Ubuntu 20.04 LTS** (mine is 20.04.6 LTS) on **Virtualbox** (mine is Virtualbox 7.0.4), and upgrade system softwares.

`sudo apt-get update`

`sudo apt-get upgrade`

2. Link 'python' command to built-in Python3.

`sudo apt install python-is-python3`

3. Install dependencies not included in the script

`sudo apt install python3-pip`

`sudo apt install git`

`sudo apt-get install screen`

4. Clone the project and run the .sh files.

Many thanks to Simon and everyone who contributed to this amazing project!

**Comment by yekurd** [comment]
hey, i had a question, did you every manage to visualise the constellation using the visualize_constellation.py script?

**Comment by tkoch96** [comment]
I fixed this error a different way --- I turned off "-Werror" in the compilation. Look at ns3-sat-sim/simulator/waf-tools/cflags.py on line 162.

**Comment by mruizfda** [comment]
Hi, I have the same building problem (using Ubuntu 22.04 and Python 3.10.12 ). Running: bash hypatia_build.sh --disable-werror I still have the same problem, any solution without changing the Ubuntu version?
